### ISSUE TITLE
Publish to npm or tag releases on GitHub

### ISSUE THREAD

**Issue by LukasDrgon** [charlestati/amplify#4]
It would be great, if you could publish this on npm or tag releases on GitHub, so that users can easily include files from a CDN such as [jsDelivr](https://www.jsdelivr.com/).

**Comment by charlestati** [comment]
Hi, @LukasDrgon! I just tagged a release on GitHub, is that all that is needed for jsDelivr?
I'll publish it on NPM when I have a bit more time.

Thanks!

**Comment by LukasDrgon** [comment]
Awesome! The files are now available at
https://cdn.jsdelivr.net/gh/charlestati/amplify@1.0/docs/

One small improvement would be using semver for GitHub tags, e.g. `1.0.0` instead `1.0`. This is needed for "auto updating" URLs such as https://cdn.jsdelivr.net/gh/charlestati/amplify@1/docs/ or https://cdn.jsdelivr.net/gh/charlestati/amplify@latest/docs/ to work. If you publish to npm, your project will also appear in search results at https://www.jsdelivr.com/, but it is not necessary.

**Comment by charlestati** [comment]
I changed the tag from `v1.0` to `v1.0.0`. I didn't know about jsDelivr, it looks very powerful!

I also published it on NPM but under the name [image-amplify](https://www.npmjs.com/package/image-amplify) as `amplify` was already taken.

Thanks for your suggestions @LukasDrgon!
